### ISSUE TITLE
The CartDeliveryGroup '<id>' does not have an OrderDeliveryMethod. 

### ISSUE THREAD

**Issue by palessard87** [forcedotcom/b2b-commerce-on-lightning-quickstart#9]
Hi there,

Trying to run the flow with basic settings and integrations.

When I get to the "Cart to Order" step, I always get this message. Debugging the flow has been no help.

I queried the CartDeliveryGroup, CartDeliveryGroupMethod objects they do have a key pointing to an OrderDeliveryMethod.

Any idea why this happens?

![image](https://user-images.githubusercontent.com/77359721/104368290-de61da00-54e9-11eb-9bcf-015cd29c23fa.png)

**Comment by palessard87** [comment]
Using the Winter21 flow by the way.

**Comment by palessard87** [comment]
Am I the only person with such an issue?

**Comment by pmaliwat** [comment]
@palessard87 We've seen this error before and, in the past, I believe it was caused by changes to the [integration Apex classes](https://github.com/forcedotcom/b2b-commerce-on-lightning-quickstart/tree/winter21/examples/checkout/integrations/classes).  The results were basically what the error said - the CartDeliveryGroup record did not that mandatory DeliveryMethodId field populated.

Though, you've check and those do exist...

Just to understand the state of your environment, have you made any changes at all to your integration Apex classes? And where did you get your integrations from?  Just make sure it's from the same branch (winter21) as where the Checkout is from.

**Comment by palessard87** [comment]
Thank you, was able to circumvent this.
